// Automatically generated by MockGen. DO NOT EDIT!
// Source: builder.go

package mock_echorequid

import (
	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo"
)

// Mock of RequestUUIDBuilder interface
type MockRequestUUIDBuilder struct {
	ctrl     *gomock.Controller
	recorder *_MockRequestUUIDBuilderRecorder
}

// Recorder for MockRequestUUIDBuilder (not exported)
type _MockRequestUUIDBuilderRecorder struct {
	mock *MockRequestUUIDBuilder
}

func NewMockRequestUUIDBuilder(ctrl *gomock.Controller) *MockRequestUUIDBuilder {
	mock := &MockRequestUUIDBuilder{ctrl: ctrl}
	mock.recorder = &_MockRequestUUIDBuilderRecorder{mock}
	return mock
}

func (_m *MockRequestUUIDBuilder) EXPECT() *_MockRequestUUIDBuilderRecorder {
	return _m.recorder
}

func (_m *MockRequestUUIDBuilder) Build(c echo.Context) (string, error) {
	ret := _m.ctrl.Call(_m, "Build", c)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockRequestUUIDBuilderRecorder) Build(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Build", arg0)
}
